### ISSUE TITLE
Broken puppies :-(

### ISSUE THREAD

**Issue by justinhelmer** [chrisdel101/place-puppy#30]
Example 1: https://place-puppy.com/300x300

![Screenshot 2023-01-05 at 2 49 54 AM](https://user-images.githubusercontent.com/1403438/210762972-7c5607d8-95be-4754-969a-0bc18121a023.png)

> Actual dimensions: 316x102, with cutoff

Example 2: https://place-puppy.com/200x300

![Screenshot 2023-01-05 at 2 50 42 AM](https://user-images.githubusercontent.com/1403438/210763103-c75cf57b-4c53-4f4d-89d0-c072ccb266de.png)

> Actual dimensions: 50x40, with cutoff

**Comment by chrisdel101** [comment]
There are issues that need fixing but it should be working again for now.

Thanks for reporting this. Please report any future errors.

**Comment by justinhelmer** [comment]
Thanks so much @chrisdel101 !
