### ISSUE TITLE
Disable CORS headers so we can embed images on websites?

### ISSUE THREAD

**Issue by justinhelmer** [chrisdel101/place-puppy#31]
👋 

I saw you recently added helmet for web security headers. No qualms there!

I wonder if you would be willing to disable CORS so that we can embed place-puppy URLs on our webpages?

```
 helmet({
  crossOriginEmbedderPolicy: false,
})
```

We use your wonderful website for testing with selenium/webdriver. The recent change breaks our automation suite.

I really don't want to move over to placekitten :( 

Thanks!

**Comment by chrisdel101** [comment]
Thanks for the feedback. I wouldn't know about things such as this otherwise. I should be able to implement this. Will comment again here again once it, or work around, is done.

**Comment by justinhelmer** [comment]
Thanks as always @chrisdel101 for the quick turnaround and willingness!

I'll hold off on fixing our tests for now.

**Comment by chrisdel101** [comment]
The whole purpose of this to embed, so it's pretty bad if that's been broken this whole time (Like 3+ weeks). It worked with the `crossorigin` tag, but I don't want that to be required.

Should be fixed now. Please let me know if not and we'll reopen. 

Thanks for letting me know about this issue.

**Comment by justinhelmer** [comment]
Wow what a quick turnaround!!

I actually was just running E2E tests and saw those tests started magically passing 🪄 . So I can confirm the fix has worked.

I really appreciate it 🙏
