### ISSUE TITLE
The site is down?

### ISSUE THREAD

**Issue by Alonski** [chrisdel101/place-puppy#4]
@chrisdel101 Not sure where else to contact you :)
https://place-puppy.com/ seems to be down.

I think not just for me :)

**Comment by chrisdel101** [comment]
Hi, thanks for contacting me and letting me know! Please let me know if it happens again. I've restarted the server and it's working again I hope.

Sorry about this. It needs maintenance to determine why it's crashing; I have not been able to do it yet.
-CHRIS

**Comment by Alonski** [comment]
Thanks for the help! Should we close this?
