### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by samdutton** [chrisdel101/place-puppy#6]
Any chance of moving place-puppy.com to HTTPS? 

(Nice work by the way — thank you!)

**Comment by chrisdel101** [comment]
Yeah, that's possible. I'll work on it

**Comment by samdutton** [comment]
Thanks!

**Comment by chrisdel101** [comment]
This is done.

**Comment by samdutton** [comment]
Thank you Chris!

**Comment by chrisdel101** [comment]
Seems to be back to https. Closing this again. 
Thanks for the suggestion and using place-puppy.com!
